spring:
  config:
    import: application-secret.yml
  data:
    redis:
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/anomaly
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # SQL 쿼리 로그 출력
  session:
    store-type: redis
    redis:
      namespace: shboard:session
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 30 * 60 * 1000 == 30일

server:
  servlet:
    session:
      cookie:
        name: JSESSIONID