version: '3.8'

services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo_service"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DEV_MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DEV_MONGO_ROOT_PASSWORD}
    volumes:
      - mongo-data:/data/db
  redis:
    image: "redis:latest"
    container_name: "redis_service"
    hostname: "redis"
    environment:
      - REDIS_PASSWORD=${DEV_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  mongo_data:
