services:
  redis:
    image: "redis:latest"
    container_name: "redis_service"
    hostname: "redis"
    environment:
      - REDIS_PASSWORD=${DEV_REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: "postgres:latest"
    container_name: "postgres_service"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DEV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DEV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DEV_POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
