spring:
  config:
    import: application-secret.yml
  data:
    redis:
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
  kafka:
    consumer:
      auto-offset-reset: earliest


