spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
#    show-sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
